## defaults to image: gitlab/gitlab-runner:alpine-${current_version}
imagePullPolicy: IfNotPresent
concurrent: 20
checkInterval: 30
terminationGracePeriodSeconds: 3600
unregisterRunners: true
rbac:
    create: true
    clusterWideAccess: true
runners:
    image: ubuntu:16.04
    privileged: true
    pollTimeout: 180
    outputLimit: 40960
    runUntagged: true
    locked: false
    builds:
      cpuLimit: 4000m
      memoryLimit: 15Gi
      cpuRequests: 4000m
      memoryRequests: 15Gi
    services:
      cpuLimit: 4000m
      memoryLimit: 15Gi
      cpuRequests: 4000m
      memoryRequests: 15Gi
